### ISSUE TITLE
Support for Right to Left reading (Manga)

### ISSUE THREAD

**Issue by Kataomoi** [Cortys/comixology-backup#13] opened 2014-08-03 00:26 UTC
I'm hoping in a future version you can add support for Manga that reads right to left. When I try to save a manga, it stalls at 0% and does nothing. I believe this is due to the different way pages advance.

**Comment by shinji257** [comment] 2015-03-21 02:29
I'm not sure if that is doing it but I notice that on graphic novels where they have you going left for the next page that the script is numbering them backwards as it is starting at the last page and moving towards the first one instead of the other way around.

I good free example of this is the Inazuman series where they have free previews that exhibit this exact behavior.

**Comment by Cortys** [comment] 2015-04-19 19:38
I was busy working on other projects lately.

Manga support will be pushed to master soon. Just started working on it in the 2.1.0 branch.

**Comment by Cortys** [comment] 2015-04-20 16:28
Could anyone give me the names of a few comics that use manga fixed format (ideally free previews)?

Thanks!

**Comment by Kataomoi** [comment] 2015-04-22 03:00
https://www.comixology.com/Boys-Over-Flowers-Season-2/comics-series/40497

There are a few chapters here that are free and read right to left.

**Comment by Cortys** [comment] 2015-04-22 16:47
@Kataomoi Thanks! Would it be acceptable if fixed format comics were exported as dual-page-images (not split up to individual pages)?

**Comment by Kataomoi** [comment] 2015-04-22 21:01
Single page preferred, but dual is definitely workable. Thanks for looking into this!

**Comment by Cortys** [comment] 2015-04-24 08:40
Fixed format mangas should be supported now.

Could you verify that (the beta is on the [2.1.0 branch](https://github.com/Cortys/comixology-backup/tree/2.1.0))?

**Comment by shinji257** [comment] 2015-04-24 11:09
I'd like to see Kataomoi's input on this but I checked this issue against a couple of mangas.  One was one I mentioned earlier that may of been related although not forced 2 page then the other was the original that used a forced "manga" format.  Both seemed to backup ok with proper numbering.  However I saw an odd issue when backing up the forced manga format.

The first time I backed it up the 1st page right after the cover was skipped.  Then it used odd numbering the rest of the way through for the images so it was numbered like this...

page000
page002
page005
page007
etc...

I turned off transitions just in case then redid it and it got it properly the next time and used even numbers. for the run.
page000
page001
page002
page004
etc...

(while typing this test a 3rd time -- also without transitions)
It did it again... Skipped the 2nd page.

(watches the download)
Oh.... it looks like it is going directly from the cover to the first 2-page spread for some reason and skipping the 2nd single page.  If you send me a message I'll gift you a copy of the manga being affected since it may be acting different than what you tested with.  The interesting bit is the issue is intermittent.  Usually re-doing the scan is enough but it doesn't appear the delay is the issue at all.  As part of my testing I did increase the delay to 700ms.

(tests using the freebies above)
Ok... I checked using the freebies and they did the same thing.  There is the cover then a single page (page 2) then it goes to 2-page format.  The script appears to be going from page 1 (cover) then directly to page 3 (first 2-page layout) skipping over page 2.

**Comment by Cortys** [comment] 2015-04-24 14:57
Thanks for the report.

I thought I fixed the page skipping bug you described. Which delay were you using when it occurred? Always 700ms?

**Comment by shinji257** [comment] 2015-04-24 15:56
At first I saw it on the default then extended it to 700.  Once I started actually watching it I never saw it hit page 2.  During the short period when the page selection was at the bottom I saw it go directly from page "1" to page 3 then continue from there.

**Comment by Cortys** [comment] 2015-04-24 16:50
Hm. That's odd. I could not reproduce the bug (tested with the freebies).

With enabled animations the cover pages were missing in my scans though. Looks like there is yet another general timing issue not related to any specific page.

**Comment by shinji257** [comment] 2015-04-24 17:50
Did you clear your cache?  It seems to only affect the first iteration.  It's still really strange.

**Comment by Cortys** [comment] 2015-04-24 18:03
Yes I did. Since both issues are quite similar I'll try to fix the ones I'm experiencing, which will hopefully fix the ones you described as well.

**Comment by Kataomoi** [comment] 2015-04-25 16:06
I can't get it past the initial setup scan (pressing single page, multipage).

**Comment by Cortys** [comment] 2015-04-25 16:08
@Kataomoi You have to do the setup with a regular (left to right) comic.

**Comment by Kataomoi** [comment] 2015-04-25 18:26
I compared the first 2 chapters (about 60 pages) and did not notice any dropped pages. From what I can tell, everything is working.

**Comment by Cortys** [comment] 2015-04-27 14:56
I just committed a major change in the latency compensation logic, which should still have the improved backup speed of the last one while supporting guided view narrative and mangas.

@shinji257 The bugs I experienced are fixed in the new implementation. Could you check if yours are fixed as well?

**Comment by Cortys** [comment] 2015-04-28 20:41
As I'm quite confident in the quality of the 2.1.0 branch, I'll release it now and consider this bug fixed.

If you should still experience issues with mangas, I'll reopen of course.

**Closed by Cortys** 2015-04-28 20:41 UTC
Labels: enhancement

**Comment by Kataomoi** [comment] 2015-04-29 02:36
Great! Thank you so much for the work on this.
