### ISSUE TITLE
Tab crashes when trying to scan after switching to Amazon sign in

### ISSUE THREAD

**Issue by ilikecake123** [Cortys/comixology-backup#47] opened 2016-02-04 21:29 UTC
Hey,
For some reason I switched over to Amazon sign in and after but after I did, the scan / setup button works opens a new tab as expected but after trying to load for a but the background tab crashes (not the browser). Worked fine before but unfortunately I can't switch back to a non-amazon account to test if it's definitely that.

I'm currently using Chrome Version 50.0.2640.0 canary (64-bit) with latest version of the extension if that helps.

**Comment by Cortys** [comment] 2016-02-05 19:58
Thanks for the report!

This issue probably isn't related to the Amazon sign in.

It is caused by `reactivateDom.js`, which replaces `window.MutationObserver` in order to prevent Comixology from preventing the extension to work properly (if that made any sense to you). This appears to be a Canary-only bug.

I'll release a patch this weekend. A quick fix would be to switch over to stable for now.

**Comment by Cortys** [comment] 2016-02-05 20:58
Fixed in [2.3.2](https://github.com/Cortys/comixology-backup/releases/tag/2.3.2).

**Closed by Cortys** 2016-02-05 20:58 UTC

**Comment by ilikecake123** [comment] 2016-02-07 12:40
Good work! Thanks very much!
