### ISSUE TITLE
Marvel Infinite Comics are not able to be backed up

### ISSUE THREAD

**Issue by BRTPOB** [Cortys/comixology-backup#25] opened 2015-01-25 03:26 UTC
I'm not sure whether it's because they're a different style or not, but Marvel's Infinite Comics such as Original Sin: Secret Avengers Infinite Comic #1 cannot be backed up, it simply hangs at 0% on page one and goes no further. I've tried with both Original Sin: Secret Avengers Infinite Comics and with Daredevil's move to San Francisco.

**Comment by Cortys** [comment] 2015-01-25 17:16
The issue is caused by the "Guided view narrative" mode, which can not be disabled in those comics.

I will look into this when I got some time. Thanks for the report!

**Comment by shinji257** [comment] 2015-03-20 23:52
I just checked this one a minute ago (bug is a couple of months old?) and while picking on my bug report I found the comic could be controlled manually when it was stuck at 0% (at least until the script realized it had loaded page 2 anyways) so here is a workaround for now since it never picks up on page 2 due to the forced transition.

If you hit right (to go to the next "page) then go back it starts the automatic routine.  Keep in mind it is best you have it starting at page 1 to minimize the page swap.  When I started at page 1 it still swapped "page" 1 and 2.  You just have to rename the files in the cbz (unzip, rename, rezip and change the extension back to cbz).

To be safe I also compared it to ensure all the pages were in order.  It does grab full pages on the transition pages.  So you get a couple odd ones in there where they made real transitions but those happen later on (oddly enough).

**Comment by Cortys** [comment] 2015-04-20 22:37
Should be fixed in 2.1.0 branch now.

Feedback would be great. Thanks!

**Comment by shinji257** [comment] 2015-04-24 10:41
I checked this and it appears to have backed up fine without any manual intervention.

**Comment by Cortys** [comment] 2015-04-24 15:00
Great!

**Comment by Cortys** [comment] 2015-04-27 14:54
I just committed a major change in the latency compensation logic, which should still have the improved backup speed of the last one while supporting guided view narrative and mangas.

To make sure everything is working as expected it would be great if someone could verify if guided view narrative mode works as expected. (no dropped pages, halting etc.) Thanks!

**Comment by Cortys** [comment] 2015-04-28 20:41
As I'm quite confident in the quality of the 2.1.0 branch, I'll release it now and consider this bug fixed.

If you should still experience issues with guided view narrative mode, I'll reopen of course.

**Closed by Cortys** 2015-04-28 20:41 UTC
Labels: bug, workaround available
